language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      compiler: g++-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
              - valgrind
              - libgtest-dev
              - libgoogle-glog-dev
              - g++-8


script:
   - g++ --version
   - source .env
   - make -C third_party/automorphism/bliss/ lib
   - make V=3
   - make check-style
