language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
              - valgrind
              - libgtest-dev
              - googletest
              - libgoogle-glog-dev
              - g++-8
              - gcc-8
              - cmake


before_script:
  - export CC=gcc-8
  - export CXX=g++-8
  - export AR=gcc-ar-8
  - export RANLIB=gcc-ranlib-8
  - export NM=gcc-nm-8

# Build gtest
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - cmake .
  - cmake --build .
  - cp lib/*.a /usr/local/lib

script:
   - source .env
   - make -C third_party/automorphism/bliss/ lib
   - make
   - make test
   - make check-style
