language: cpp
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - valgrind
    - libgtest-dev
    - libgoogle-glog-dev

matrix:
  include:
    - os: linux
      compiler: gcc

script:
  - source .env
  - make -C third_party/automorphism/bliss/ lib
  - make
  - make check-style
