language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
              - valgrind
              - libgtest-dev
              - libgoogle-glog-dev
              - g++-8
              - gcc-8
          env: GCCVER='8'


before_script:
  - export CC=gcc-${GCCVER}
  - export CXX=g++-${GCCVER}
  - export AR=gcc-ar-${GCCVER}
  - export RANLIB=gcc-ranlib-${GCCVER}
  - export NM=gcc-nm-${GCCVER}

script:
   - g++ --version
   - source .env
   - make -C third_party/automorphism/bliss/ lib
   - make V=3
   - make check-style
