language: cpp
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - valgrind
    - libgtest-dev
    - libgoogle-glog-dev
    - g++-7

matrix:
  include:
    - os: linux
      compiler: gcc-7

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

script:
  - source .env
  - make -C third_party/automorphism/bliss/ lib
  - make
  - make check-style
