language: cpp
dist: trusty
sudo: false

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
    - valgrind
    - libgtest-dev
    - libgoogle-glog-dev
    - g++-7

matrix:
  include:
    - os: linux
      compiler: gcc-7


script:
  - alias g++="/usr/bin/g++-7"
  - which g++
  - source .env
  - make -C third_party/automorphism/bliss/ lib
  - make
  - make check-style
