language: cpp
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
              - valgrind
              - libgtest-dev
              - libgoogle-glog-dev
              - g++-8
          env: GCCVVER='8'


before_script:
  - export AR=gcc-ar-${GCCVER} ; fi
  - export RANLIB=gcc-ranlib-${GCCVER} ; fi
  - export NM=gcc-nm-${GCCVER} ; fi

script:
   - g++ --version
   - source .env
   - make -C third_party/automorphism/bliss/ lib
   - make V=3
   - make check-style
