language: cpp
dist: trusty
sudo: false

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
    - valgrind
    - libgtest-dev
    - libgoogle-glog-dev
    - g++-8

matrix:
  include:
    - os: linux
      compiler: gcc-8


  script:
   - source .env
   - make -C third_party/automorphism/bliss/ lib
   - alias g++="/usr/bin/g++-8" && make V=3
   - make check-style
